# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 08:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atstrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.FloatField()),
                ('lidz', models.FloatField()),
                ('datums', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Darba_laiks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datums', models.DateField()),
                ('no', models.FloatField(default=9.0)),
                ('lidz', models.FloatField(default=18.0)),
                ('ir_mainits', models.BooleanField(default=False)),
                ('lietotajs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Iemesls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slimiba', models.BooleanField(default=False)),
                ('atvalinajums', models.BooleanField(default=False)),
                ('lekcijas', models.BooleanField(default=False)),
                ('darbs_no_majam', models.BooleanField(default=False)),
                ('mazaka_slodze', models.BooleanField(default=False)),
                ('cits', models.BooleanField(default=False)),
                ('darba_laiks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darba_laiks.Darba_laiks')),
                ('lietotajs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='atstrada',
            name='darba_laiks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darba_laiks.Darba_laiks'),
        ),
        migrations.AddField(
            model_name='atstrada',
            name='iemesls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darba_laiks.Iemesls'),
        ),
        migrations.AddField(
            model_name='atstrada',
            name='lietotajs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
