# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darba_laiks', '0005_auto_20170228_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atstrada',
            name='lidz',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='atstrada',
            name='no',
            field=models.TimeField(),
        ),
    ]
