# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darba_laiks', '0009_auto_20170320_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(default='http://127.0.0.1:8000/media/IMG_0322.JPG_S2z2i76.jpg', upload_to=b''),
        ),
    ]
