# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darba_laiks', '0011_auto_20170320_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
