# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darba_laiks', '0012_auto_20170320_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(default='settings.MEDIA_ROOT/avatar.jpg', upload_to=b''),
        ),
    ]
