# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darba_laiks', '0021_auto_20170320_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(default='/avatar.jpg', upload_to=b''),
        ),
    ]
