# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darba_laiks', '0022_auto_20170321_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darba_laiks',
            name='datums',
            field=models.DateField(blank=True, null=True),
        ),
    ]
