# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 09:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('darba_laiks', '0023_auto_20170415_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saglabatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lietotajs_kurs_pievienoja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lietotajs_kurs_pievienoja', to=settings.AUTH_USER_MODEL)),
                ('lietotajs_kuru_pievienoja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lietotajs_kuru_pievienoja', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='darba_laiks',
            name='datums',
            field=models.DateField(),
        ),
    ]
