# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darba_laiks', '0024_auto_20170417_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atstrada',
            name='datums',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atstrada',
            name='lidz',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atstrada',
            name='no',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
