# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darba_laiks', '0026_virsstundas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darba_laiks',
            name='datums',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='darba_laiks',
            name='lidz',
            field=models.TimeField(blank=True, default='18:00', null=True),
        ),
        migrations.AlterField(
            model_name='darba_laiks',
            name='no',
            field=models.TimeField(blank=True, default='9:00', null=True),
        ),
    ]
