# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darba_laiks', '0027_auto_20170524_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='virsstundas',
            name='statuss',
            field=models.CharField(default='gaida', max_length=50),
        ),
    ]
